"""preference notificaiton

Revision ID: e5bfe10e1af5
Revises: de089d1be09e
Create Date: 2025-12-04 23:37:14.063624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e5bfe10e1af5'
down_revision: Union[str, None] = 'de089d1be09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_preferences')
    # ### end Alembic commands ###
