"""Add jellyfin fields to users

Revision ID: 7098b65d2df8
Revises: 4cb8193d93c1
Create Date: 2025-12-28 14:07:21.073017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7098b65d2df8'
down_revision: Union[str, None] = '4cb8193d93c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jellyfin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('jellyfin_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jellyfin_api_key')
    op.drop_column('users', 'jellyfin_url')
    # ### end Alembic commands ###
