"""Ajout du tag is_in_jellyfin

Revision ID: da3e2e6aa97a
Revises: 7098b65d2df8
Create Date: 2025-12-28 15:11:20.448783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'da3e2e6aa97a'
down_revision: Union[str, None] = '7098b65d2df8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_media_entries', sa.Column('is_in_jellyfin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_media_entries', 'is_in_jellyfin')
    # ### end Alembic commands ###
