"""Ajout de la colonne translation in média

Revision ID: 9e585fdefd6f
Revises: e5bfe10e1af5
Create Date: 2025-12-05 14:34:43.628574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e585fdefd6f'
down_revision: Union[str, None] = 'e5bfe10e1af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'translations')
    # ### end Alembic commands ###
