"""Add genre_ids column and remove media_genres table

Revision ID: f409c6b3de20
Revises: 
Create Date: 2025-11-13 23:13:14.635259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f409c6b3de20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_genres')
    op.add_column('media', sa.Column('genre_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'genre_ids')
    op.create_table('media_genres',
    sa.Column('media_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_media_type', postgresql.ENUM('MOVIE', 'TV', name='mediatype'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genre_id', 'genre_media_type'], ['genres.id', 'genres.media_type'], name=op.f('media_genres_genre_id_genre_media_type_fkey')),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('media_genres_media_id_fkey')),
    sa.PrimaryKeyConstraint('media_id', 'genre_id', 'genre_media_type', name=op.f('media_genres_pkey'))
    )
    # ### end Alembic commands ###
