"""added_actors_and_directors

Revision ID: dfc7c018f8f1
Revises: 75a0530f6d8d
Create Date: 2025-11-17 14:53:29.762325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfc7c018f8f1'
down_revision: Union[str, None] = '75a0530f6d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_media_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_table('comments')
    op.add_column('media', sa.Column('actors', sa.JSON(), nullable=True))
    op.add_column('media', sa.Column('directors', sa.JSON(), nullable=True))
    op.alter_column('reviews', 'content',
               existing_type=sa.VARCHAR(length=5000),
               nullable=True)
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'content',
               existing_type=sa.VARCHAR(length=5000),
               nullable=False)
    op.drop_column('media', 'directors')
    op.drop_column('media', 'actors')
    op.create_table('comments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=5000), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('comments_media_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('comments_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_media_id'), 'comments', ['media_id'], unique=False)
    # ### end Alembic commands ###
