"""add color field to genre table

Revision ID: 4cb8193d93c1
Revises: a7d84baf946a
Create Date: 2025-12-25 17:30:04.760695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4cb8193d93c1'
down_revision: Union[str, None] = 'a7d84baf946a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Ajouter la colonne comme nullable
    op.add_column('genres', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True))

    # 2. Mettre à jour toutes les lignes existantes avec une valeur par défaut
    op.execute("UPDATE genres SET color = '#808080' WHERE color IS NULL")

    # 3. Rendre la colonne NOT NULL
    op.alter_column('genres', 'color', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('genres', 'color')
    # ### end Alembic commands ###
