"""update etats de enums

Revision ID: 2a609a0a3339
Revises: 6a7d5e068404
Create Date: 2025-12-12 17:00:09.026549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a609a0a3339'
down_revision: Union[str, None] = '6a7d5e068404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE activitytype ADD VALUE IF NOT EXISTS 'CHALLENGE_JOINED'")
    op.execute("ALTER TYPE activitytype ADD VALUE IF NOT EXISTS 'CHALLENGE_COMPLETED_EPISODE'")
    op.execute("ALTER TYPE activitytype ADD VALUE IF NOT EXISTS 'CHALLENGE_MILESTONE'")
    op.execute("ALTER TYPE activitytype ADD VALUE IF NOT EXISTS 'CHALLENGE_LEFT'")
    op.execute("ALTER TYPE activitytype ADD VALUE IF NOT EXISTS 'CHALLENGE_FINISHED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
