"""add is_public and remove obsolete tables

Revision ID: 6dfcdf5f8e14
Revises: f409c6b3de20
Create Date: 2025-11-14 13:11:19.992904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dfcdf5f8e14'
down_revision: Union[str, None] = 'f409c6b3de20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge_participations', if_exists=True)
    op.drop_table('group_memberships', if_exists=True)
    op.drop_index(op.f('ix_groups_creator_id'), table_name='groups', if_exists=True)
    op.drop_index(op.f('ix_groups_name'), table_name='groups', if_exists=True)
    op.drop_table('groups', if_exists=True)
    op.drop_column('media', 'genres', if_exists=True)
    op.drop_column('user_media_entries', 'progress', if_exists=True)
    # Ajouter la colonne avec une valeur par défaut côté serveur
    op.add_column('users', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # Optionnel : supprimer le server_default après la création si tu veux gérer les défauts côté application
    op.alter_column('users', 'is_public', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_public')
    op.add_column('user_media_entries', sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('media', sa.Column('genres', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('groups',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('group_type', postgresql.ENUM('PUBLIC_GLOBAL', 'PUBLIC_COMMUNITY', 'PRIVATE', name='grouptype'), autoincrement=False, nullable=False),
    sa.Column('avatar_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_challenge', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('media_list', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='groups_creator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.create_index(op.f('ix_groups_creator_id'), 'groups', ['creator_id'], unique=False)
    op.create_table('group_memberships',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('group_memberships_group_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('group_memberships_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('group_memberships_pkey'))
    )
    op.create_table('challenge_participations',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_media', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('joined_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('challenge_participations_group_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('challenge_participations_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('challenge_participations_pkey'))
    )
    # ### end Alembic commands ###
