build:docker:
  stage: build
  image: docker:29
  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock" 
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "🐳 Connecting to Host Docker..."
    - docker info
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  script:
    - |
      echo "🏗️ Construction de l'image Docker..."
      docker build --no-cache -t $DOCKER_IMAGE -t $DOCKER_IMAGE_LATEST .
      
      echo "📤 Push de l'image vers les registres..."
      docker push $DOCKER_IMAGE
      docker push $DOCKER_IMAGE_LATEST
      
      echo "build_status=success" >> $PIPELINE_STATUS_FILE
      echo "✅ Image Docker construite et poussée avec succès"
  after_script:
    - docker logout
    - docker logout $CI_REGISTRY
  artifacts:
    when: always
    paths:
      - $PIPELINE_STATUS_FILE
    expire_in: 1 day